[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "marketmind"
version = "0.1.0"
description = "Modern Python project template"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "*"
plotly = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pytest = "*"
pandas = "*"
yfinance = "*"
mypy = "*"
pandas-stubs = "*"
pyarrow = "*"
coverage = "*"
pytest-cov = "*"
black = "*"
pre-commit = "*"

[project]
name = "marketmind"
description = "Modern Python project template"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "streamlit",
    "plotly",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "pandas",
    "yfinance",
    "mypy",
    "pandas-stubs",
    "pyarrow",
    "coverage",
    "pytest-cov",
    "black",
    "pre-commit",
]

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = ["E", "F"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]

[tool.mypy]
python_version = "3.11"
strict = true
files = ["src"]
mypy_path = "src"

[[tool.mypy.overrides]]
module = "yfinance"
ignore_missing_imports = true

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.black]
target-version = ["py311"]
line-length = 88
