name: CI

on: [push, pull_request]

env:
  COV_MIN: "80"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.8.2

      - name: Install deps (dev)
        run: poetry install --with dev --no-interaction --no-root

      - name: Ruff strict
        run: poetry run ruff check .

      - name: Black formatting check
        run: poetry run black --check .

      - name: mypy static typing
        run: poetry run mypy src

      - name: Pytest + coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml --cov-fail-under=$COV_MIN

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      - name: Export requirements.txt for Streamlit deploy
        run: poetry export -f requirements.txt --without-hashes -o requirements.txt
