name: Cognitive Monitor

on:
  pull_request:
    types:
      - closed

jobs:
  monitor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Analyze cognitive load
        run: |
          python analyze_cognitive_load.py || true
      - name: Fail on break file
        run: |
          if [ -f .you-need-a-break ]; then exit 1; fi
