name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
          poetry add --group dev bandit
      - name: Bandit
        run: poetry run bandit -r src -lll
